## Copyright (C) 2023 Jonathan D. Magasin
##
## This file describes packages required to run the nifH ASV workflow.
##
## Maintainer notes:
## This yml must mirror the DADA nifH pipeline's environment_DADA2_nifH_with_ancillary.yml, and add
## the few additional workflow-specific packages in the final section. Mirroring is not ideal but is
## safer/simpler for the user compared to cloning DADA2_nifH and adding each new pacakge.
## Note also that an earlier solution was to --stack nifH_ASV_workflow on top of
## DADA2_nifH. However, that only works for conda packages.  R and python libraries installed in
## DADA2_nifH would disappear if there was an R or python in nifH_ASV_workflow (and my workaround,
## adding them to DADA2_nifH, was a hack).
##
name: nifH_ASV_workflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core DADA2 nifH pipeline
  - r-base             >=4.1.3
  - bioconductor-dada2 >=1.20.0
  - r-vegan            >=2.5.7
  - cutadapt           >=3.4
  - fraggenescan       >=1.31
  - hmmer              >=3.3.2

  # DADA2 nifH pipeline ancillary scripts
  #                                 Needed by:
  - r-digest           >=0.6.27 #  assignAUIDs2ASVs.R
  - fastqc             >=0.12.1 #  do_fastqc.sh
  - vsearch            >=2.22.1 #  check_chimera_denovo.sh
  - blast              >=2.14.0 #  check_nifH_contaminants.sh, classifyNifH.sh, blast{nARB2017,xGenome879}.sh
  - biopython          >=1.81 #  assignNifHclustersToNuclSeqs.sh

  # External tools required by the ASV workflow
  - make               >=4.3 # Most stages use Makefiles
  - snakemake          >=7.32.4 # CMAP stage uses Snakemake
  - pandas             =2.1.2 # Used in AnnotateAuids
  - r-lutz             >=0.3.1 # Needed by GatherMetadata
  - r-tidyverse        >=1.3 # Needed by WorkspaceStartup
